from pathlib import Path

from jinja2 import Environment, FileSystemLoader

TEMPLATE_DIR = Path(__file__).resolve().parents[1] / "ansible" / "roles" / "caddy" / "templates"


def _render() -> str:
    env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), keep_trailing_newline=True)
    return env.get_template("Caddyfile.j2").render(
        acme_email="contact@personal.example",
        fleet_domain="fleet.personal.example",
        fleet_daemon_port=8765,
        fleet_caddy_snippet_dir="/etc/caddy/fleet",
        ddev_router_http_port=8080,
        ddev_router_https_port=8443,
    )


def test_caddyfile_no_longer_exposes_typesense_path_route():
    out = _render()
    assert "/_typesense" not in out
    assert "handle /_typesense/* {" not in out


def test_caddyfile_keeps_web_catchall():
    out = _render()
    assert "reverse_proxy 127.0.0.1:8080" in out
    assert "reverse_proxy 127.0.0.1:8765" in out


def test_caddyfile_no_longer_has_a_static_typesense_site_block():
    """The static *.{{ fleet_domain }}:9108 block is gone — named-port
    exposure (Typesense included) is now entirely dynamic, generated by
    fleet.core.caddyports and imported via glob (see the next test)."""
    out = _render()
    assert "9108" not in out
    assert "8108" not in out


def test_caddyfile_imports_fleet_owned_port_snippets_via_glob():
    """Unlike the dashboard's literal admin-auth import, the ports/ import
    MUST be a glob — the directory can legitimately be empty (no project
    has opted into a named port yet), and only a glob matching zero files
    is a silent Caddy no-op; a literal missing path is a hard error (same
    reasoning as the instances/*.conf per-instance auth import below)."""
    out = _render()
    assert "import /etc/caddy/fleet/ports/*.conf" in out


def test_caddyfile_admin_auth_imports_fleet_owned_snippet_not_inline_hash():
    out = _render()
    assert "import /etc/caddy/fleet/admin-auth.conf" in out
    # the hash must never be inlined directly in the rendered Caddyfile —
    # rotation must not require re-rendering/re-deploying this template
    assert "$2a$" not in out
    assert "$2b$" not in out


def test_caddyfile_admin_auth_import_is_inside_protected_basic_auth_block():
    out = _render()
    site_start = out.index("fleet.personal.example {")
    site_end = out.index("\n}", site_start)
    site_block = out[site_start:site_end]
    assert "basic_auth @protected {" in site_block
    assert "import /etc/caddy/fleet/admin-auth.conf" in site_block


def test_caddyfile_keeps_websocket_exemption_for_basic_auth():
    out = _render()
    assert "@protected not path /ws/*" in out


def test_caddyfile_instances_site_imports_per_instance_auth_snippets_via_glob():
    """Unlike the dashboard's literal admin-auth import, the per-instance
    import MUST be a glob — the instances/ dir can legitimately be empty
    (zero instances with auth enabled), and only a glob matching zero
    files is a silent Caddy no-op; a literal missing path is a hard
    validate/reload error."""
    out = _render()
    site_start = out.index("*.fleet.personal.example {")
    site_end = out.index("\n}", site_start)
    site_block = out[site_start:site_end]
    assert "import /etc/caddy/fleet/instances/*.conf" in site_block


def test_caddyfile_instances_import_uses_wildcard_not_a_single_literal_file():
    out = _render()
    assert "*.conf" in out
    assert "import /etc/caddy/fleet/instances/admin-auth.conf" not in out
